export const ROLES = {
  BIOMETRIC_CANDIDATE_ATTENDANCE: 'BIOMETRIC_CANDIDATE_ATTENDANCE',
  BIOMETRIC_STAFF_ATTENDANCE: 'BIOMETRIC_STAFF_ATTENDANCE'
}

export const ALLOW_QR_SCAN = 'is_allow_qr_scan'